runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: public/index.html
  upload: public/index\.html

- url: /oauth/.*
  script: twitter_oauth_handler.app

- url: /update
  script: twitter_oauth_handler.app

- url: /
  static_dir: public

error_handlers:
  - error_code: dos_api_denial
    file: dos.html
