application: arduino-tweet
version: 1
runtime: python
api_version: 1
threadsafe: no

handlers:
- url: /
  static_files: public/index.html
  upload: public/index\.html

- url: /oauth/.*
  script: twitter_oauth_handler.py

- url: /update
  script: twitter_oauth_handler.py

- url: /
  static_dir: public
